### ISSUE TITLE
Does cryo_fit2 depend on gromacs?

### ISSUE THREAD

**Issue by changephilip** [cryoFIT/cryo_fit2#1]
Hello!
As i know, cryo_fit depended on gromacs.
If i want to use cryo_fit2, do I also need to configure gromacs ?

**Comment by kimdn** [comment]
> Hello!
> As i know, cryo_fit depended on gromacs.
> If i want to use cryo_fit2, do I also need to configure gromacs ?

No, cryo_fit2 has nothing to do with gromacs. @changephilip 
See attached documents.

[CryoFit2_ Fitting to a Cryo-EM Map using Phenix Dynamics.pdf](https://github.com/cryoFIT/cryo_fit2/files/2634080/CryoFit2_.Fitting.to.a.Cryo-EM.Map.using.Phenix.Dynamics.pdf)
[Install Cryo_fit2.pdf](https://github.com/cryoFIT/cryo_fit2/files/2634081/Install.Cryo_fit2.pdf)
[tutorial.pdf](https://github.com/cryoFIT/cryo_fit2/files/2634082/tutorial.pdf)
