### ISSUE TITLE
how to include ligands in cryo_fit2

### ISSUE THREAD

**Issue by GangyuSun** [cryoFIT/cryo_fit2#11]
Hi,
Is there any method to give the ligand restraint file to cryo_fit2?  The restraint file is not supported by the default PHIL of cryo_fit2.
the erros is something like :
`Sorry: Fatal problems interpreting model file:
  Number of atoms with unknown nonbonded energy type symbols: 59
    Please edit the model file to resolve the problems and/or supply a
    CIF file with matching restraint definitions, along with
    apply_cif_modification and apply_cif_link parameter definitions
    if necessary.`
Thanks for any help!

**Comment by girodat** [comment]
Hi Gangyu, 

Sorry to say we currently don't have any ligand support in cryo_fit2. We are going to work on generating methods/libraries for cryo_fit ligands but haven't implemented it yet. 
Often it is best to use cryo_fit or cryo_fit2 to model large scale conformational changes and then use ligand fitting tools in phenix to properly position ligands such as Elbow or LigandFit etc. 

Thanks,
Dylan

**Comment by GangyuSun** [comment]
Okay, got it! Thanks for your response!
Gangyu
