### ISSUE TITLE
Cannot import name change_default_phil_values

### ISSUE THREAD

**Issue by changephilip** [cryoFIT/cryo_fit2#2]
Hello!
When running phenix.cryo_fit2 (sh run_me_it_will_take_about_100_seconds.sh),
the program reported error like below:

from libtbx.phil import change_default_phil_values
ImportError: cannot import name change_default_phil_values

I search "change_default_phil_values" under xxx/phenix-xxx/ folder , and find nothing useful.
I also checked libtbx.phil with help() in python, "change_default_phil_values" was also not found.

**Comment by kimdn** [comment]
Hi @changephilip 

I believe that change_default_phil_values was recently added by Billy.
When I tried it in my old phenix, I couldn't use it as well.

But recent phenix version (like phenix-dev-3304) had no problem.
I will close the issue, but let me know if you still has a problem even with a recent phenix.

Thank you

**Comment by changephilip** [comment]
Thank you @kimdn 
I download the phenix-dev and cryofit2 works well now.
